[package]
name = "monkey-lang"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "lib"
path = "src/lib/mod.rs"

[[bin]]
name = "repl"
path = "src/bin/repl.rs"

[[bin]]
name = "monkey_lang"
path = "src/bin/interpreter.rs"
